# Generated by Django 2.1.7 on 2019-11-27 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(verbose_name='重要度')),
                ('link', models.TextField(max_length=255, verbose_name='リンク先')),
                ('memo', models.TextField(blank=True, max_length=255, verbose_name='備考')),
            ],
            options={
                'db_table': 'links',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='links',
            name='tourokusha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='boxlinks.User', verbose_name='USER'),
        ),
    ]
