# Generated by Django 2.1.7 on 2019-11-27 13:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boxlinks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='tourokusha',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='category_name',
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True, verbose_name='user_name'),
            preserve_default=False,
        ),
    ]
